/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/': RouteRecordInfo<'/dashboard/analysis/', '/dashboard/analysis', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/chart-card': RouteRecordInfo<'/dashboard/analysis/components/chart-card', '/dashboard/analysis/components/chart-card', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/custom-line': RouteRecordInfo<'/dashboard/analysis/components/custom-line', '/dashboard/analysis/components/custom-line', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/custom-ring-progress': RouteRecordInfo<'/dashboard/analysis/components/custom-ring-progress', '/dashboard/analysis/components/custom-ring-progress', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/introduce-row': RouteRecordInfo<'/dashboard/analysis/components/introduce-row', '/dashboard/analysis/components/introduce-row', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/numberInfo/number-info': RouteRecordInfo<'/dashboard/analysis/components/numberInfo/number-info', '/dashboard/analysis/components/numberInfo/number-info', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/offline-data': RouteRecordInfo<'/dashboard/analysis/components/offline-data', '/dashboard/analysis/components/offline-data', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/proportion-sales': RouteRecordInfo<'/dashboard/analysis/components/proportion-sales', '/dashboard/analysis/components/proportion-sales', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/sales-card': RouteRecordInfo<'/dashboard/analysis/components/sales-card', '/dashboard/analysis/components/sales-card', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/top-search': RouteRecordInfo<'/dashboard/analysis/components/top-search', '/dashboard/analysis/components/top-search', Record<never, never>, Record<never, never>>,
    '/dashboard/analysis/components/trend/trend': RouteRecordInfo<'/dashboard/analysis/components/trend/trend', '/dashboard/analysis/components/trend/trend', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/': RouteRecordInfo<'/dashboard/monitor/', '/dashboard/monitor', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/': RouteRecordInfo<'/dashboard/workplace/', '/dashboard/workplace', Record<never, never>, Record<never, never>>,
    '/exception/403/': RouteRecordInfo<'/exception/403/', '/exception/403', Record<never, never>, Record<never, never>>,
    '/exception/404/': RouteRecordInfo<'/exception/404/', '/exception/404', Record<never, never>, Record<never, never>>,
    '/exception/500/': RouteRecordInfo<'/exception/500/', '/exception/500', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
  }
}
