/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('antdv-next')['Avatar']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACol: typeof import('antdv-next')['Col']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutFooter: typeof import('antdv-next')['LayoutFooter']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AppContent: typeof import('./../src/components/layouts/AppContent.vue')['default']
    AppFooter: typeof import('./../src/components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/layouts/AppHeader.vue')['default']
    AppLayout: typeof import('./../src/components/AppLayout.vue')['default']
    AppSider: typeof import('./../src/components/layouts/AppSider.vue')['default']
    AppstoreOutlined: typeof import('@antdv-next/icons')['AppstoreOutlined']
    AResult: typeof import('antdv-next')['Result']
    ARow: typeof import('antdv-next')['Row']
    AStatistic: typeof import('antdv-next')['Statistic']
    ASwitch: typeof import('antdv-next')['Switch']
    ATabs: typeof import('antdv-next')['Tabs']
    ATooltip: typeof import('antdv-next')['Tooltip']
    AWatermark: typeof import('antdv-next')['Watermark']
    HasWatermark: typeof import('./../src/components/layouts/HasWatermark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDrawer: typeof import('./../src/components/layouts/SettingsDrawer.vue')['default']
  }
}
